-- 1. DROP Existing Tables if any
DROP TABLE IF EXISTS borrowing_history CASCADE;
DROP TABLE IF EXISTS reading_list_items CASCADE;
DROP TABLE IF EXISTS reading_lists CASCADE;
DROP TABLE IF EXISTS publication_reviews CASCADE;
DROP TABLE IF EXISTS notifications CASCADE;
DROP TABLE IF EXISTS acquisition_requests CASCADE;
DROP TABLE IF EXISTS branch_transfers CASCADE;
DROP TABLE IF EXISTS quality_checks CASCADE;
DROP TABLE IF EXISTS book_holds CASCADE;
DROP TABLE IF EXISTS reservation_queue CASCADE;
DROP TABLE IF EXISTS borrowing_records CASCADE;
DROP TABLE IF EXISTS inventory_copies CASCADE;
DROP TABLE IF EXISTS publication_subjects CASCADE;
DROP TABLE IF EXISTS publication_authors CASCADE;
DROP TABLE IF EXISTS books CASCADE;
DROP TABLE IF EXISTS publications CASCADE;
DROP TABLE IF EXISTS subjects CASCADE;
DROP TABLE IF EXISTS authors CASCADE;
DROP TABLE IF EXISTS owner_settings CASCADE;
DROP TABLE IF EXISTS admin_profiles CASCADE;
DROP TABLE IF EXISTS user_accounts CASCADE;
DROP TABLE IF EXISTS members CASCADE;
DROP TABLE IF EXISTS membership_plans CASCADE;
DROP TABLE IF EXISTS branches CASCADE;

-- 2. CREATE Tables using Postgres Native Syntax
CREATE TABLE branches (
    branch_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_name VARCHAR(100) UNIQUE NOT NULL,
    address_line VARCHAR(255),
    contact_number VARCHAR(30),
    branch_status VARCHAR(20) DEFAULT 'ACTIVE'
);

INSERT INTO branches (branch_name, address_line) VALUES
('Central Library', 'Main Campus'),
('Engineering Library', 'Engineering Block'),
('Research Library', 'Research Wing');

CREATE TABLE membership_plans (
    membership_plan_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_name VARCHAR(30) UNIQUE NOT NULL,
    monthly_cost DECIMAL(10,2),
    max_active_borrows INT,
    reservation_limit INT,
    hold_duration_hours INT,
    queue_priority INT,
    cross_branch_priority CHAR(1),
    reading_list_limit INT
);

INSERT INTO membership_plans (plan_name, monthly_cost, max_active_borrows, reservation_limit, hold_duration_hours, queue_priority, cross_branch_priority, reading_list_limit) VALUES
('STANDARD', 299.00, 3, 5, 24, 0, 'N', 1),
('PREMIUM', 799.00, 8, 15, 72, 1, 'Y', 10);

CREATE TABLE members (
    member_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(50),
    last_name VARCHAR(50),
    email VARCHAR(100) UNIQUE,
    phone_number VARCHAR(20),
    home_branch_id INT REFERENCES branches(branch_id),
    preferred_branch_id INT REFERENCES branches(branch_id),
    membership_plan_id INT REFERENCES membership_plans(membership_plan_id),
    join_date DATE DEFAULT CURRENT_DATE,
    active_status CHAR(1) DEFAULT 'Y'
);

CREATE TABLE user_accounts (
    account_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(100) UNIQUE,
    email VARCHAR(100) UNIQUE,
    password_hash VARCHAR(255),
    password_salt VARCHAR(255),
    role_type VARCHAR(20),
    member_id INT REFERENCES members(member_id),
    branch_id INT REFERENCES branches(branch_id),
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    active_status CHAR(1) DEFAULT 'Y'
);

CREATE TABLE admin_profiles (
    admin_profile_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id INT UNIQUE REFERENCES user_accounts(account_id),
    branch_id INT REFERENCES branches(branch_id),
    salary_amount DECIMAL(12,2),
    hire_date DATE
);

CREATE TABLE owner_settings (
    setting_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fine_per_day DECIMAL(10,2),
    premium_membership_cost DECIMAL(10,2),
    standard_membership_cost DECIMAL(10,2),
    standard_hold_hours INT,
    premium_hold_hours INT,
    updated_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE authors (
    author_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(50),
    last_name VARCHAR(50),
    biography VARCHAR(1000)
);

CREATE TABLE subjects (
    subject_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject_name VARCHAR(100) UNIQUE
);

CREATE TABLE publications (
    publication_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(200),
    publication_year INT,
    publisher_name VARCHAR(100),
    language_name VARCHAR(50),
    publication_type VARCHAR(20),
    popularity_score INT DEFAULT 0,
    publication_status VARCHAR(30) DEFAULT 'AVAILABLE'
);

CREATE TABLE books (
    publication_id INT PRIMARY KEY REFERENCES publications(publication_id),
    isbn VARCHAR(30) UNIQUE,
    edition_name VARCHAR(50),
    page_count INT
);

CREATE TABLE publication_authors (
    publication_id INT REFERENCES publications(publication_id),
    author_id INT REFERENCES authors(author_id),
    author_order INT,
    PRIMARY KEY(publication_id, author_id)
);

CREATE TABLE publication_subjects (
    publication_id INT REFERENCES publications(publication_id),
    subject_id INT REFERENCES subjects(subject_id),
    PRIMARY KEY(publication_id, subject_id)
);

CREATE TABLE inventory_copies (
    copy_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    publication_id INT REFERENCES publications(publication_id),
    branch_id INT REFERENCES branches(branch_id),
    copy_number INT,
    copy_condition VARCHAR(20),
    copy_status VARCHAR(40),
    floor_number INT,
    section_code VARCHAR(20),
    shelf_number VARCHAR(20),
    rack_number VARCHAR(20),
    position_number VARCHAR(20),
    qr_identifier VARCHAR(100),
    barcode_identifier VARCHAR(100),
    acquisition_date DATE DEFAULT CURRENT_DATE
);

CREATE TABLE borrowing_records (
    borrow_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    copy_id INT REFERENCES inventory_copies(copy_id),
    member_id INT REFERENCES members(member_id),
    borrowed_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    due_date TIMESTAMP,
    returned_date TIMESTAMP,
    borrow_status VARCHAR(30),
    fine_amount DECIMAL(10,2)
);

CREATE TABLE reservation_queue (
    reservation_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id INT REFERENCES members(member_id),
    publication_id INT REFERENCES publications(publication_id),
    preferred_branch_id INT REFERENCES branches(branch_id),
    assigned_branch_id INT REFERENCES branches(branch_id),
    queue_position INT,
    reservation_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    hold_expiry TIMESTAMP,
    reservation_status VARCHAR(30)
);

CREATE TABLE book_holds (
    hold_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reservation_id INT REFERENCES reservation_queue(reservation_id),
    copy_id INT REFERENCES inventory_copies(copy_id),
    member_id INT REFERENCES members(member_id),
    hold_created TIMESTAMP,
    hold_expiry TIMESTAMP,
    hold_status VARCHAR(30)
);

CREATE TABLE quality_checks (
    quality_check_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    copy_id INT REFERENCES inventory_copies(copy_id),
    previous_condition VARCHAR(20),
    updated_condition VARCHAR(20),
    remarks VARCHAR(500),
    inspection_date TIMESTAMP
);

CREATE TABLE branch_transfers (
    transfer_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    copy_id INT REFERENCES inventory_copies(copy_id),
    source_branch_id INT REFERENCES branches(branch_id),
    destination_branch_id INT REFERENCES branches(branch_id),
    transfer_status VARCHAR(30),
    requested_date TIMESTAMP,
    arrival_date TIMESTAMP,
    requested_by_member_id INT REFERENCES members(member_id)
);

CREATE TABLE acquisition_requests (
    acquisition_request_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id INT REFERENCES members(member_id),
    requested_title VARCHAR(200),
    requested_author VARCHAR(200),
    requested_isbn VARCHAR(30),
    preferred_branch_id INT REFERENCES branches(branch_id),
    priority_level VARCHAR(20),
    request_status VARCHAR(30)
);

CREATE TABLE notifications (
    notification_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id INT REFERENCES members(member_id),
    notification_type VARCHAR(50),
    title VARCHAR(200),
    message_body VARCHAR(1000),
    read_status CHAR(1),
    branch_id INT REFERENCES branches(branch_id),
    created_date TIMESTAMP
);

CREATE TABLE publication_reviews (
    review_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    publication_id INT REFERENCES publications(publication_id),
    member_id INT REFERENCES members(member_id),
    rating_value INT,
    review_text VARCHAR(1000)
);

CREATE TABLE reading_lists (
    reading_list_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id INT REFERENCES members(member_id),
    list_name VARCHAR(100),
    visibility_status VARCHAR(20)
);

CREATE TABLE reading_list_items (
    item_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reading_list_id INT REFERENCES reading_lists(reading_list_id),
    publication_id INT REFERENCES publications(publication_id)
);

CREATE TABLE borrowing_history (
    history_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id INT REFERENCES members(member_id),
    copy_id INT REFERENCES inventory_copies(copy_id),
    publication_id INT REFERENCES publications(publication_id),
    borrowed_date TIMESTAMP,
    returned_date TIMESTAMP,
    days_kept INT,
    fine_paid DECIMAL(10,2)
);
